CREATE DATABASE IF NOT EXISTS mecanica DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE mecanica;
CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  telefone VARCHAR(30) NOT NULL,
  cpf_usuario VARCHAR(80) NOT NULL UNIQUE,
  placa_hash VARCHAR(255) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;